### ISSUE TITLE
Add a better gif.

### ISSUE THREAD

**Issue by Rupeshiya** [Rupeshiya/FunPacketCli#3]
Add the gif better than given now which will include the installation of fun_packet and all the commands sequentially same as given in readme.md.

**Comment by estevanjantsk** [comment]
I'll do this o//. Assignee that to me, please. 🗡

**Comment by Rupeshiya** [comment]
sure @estevanjantsk  go ahead.

**Comment by sterjoski** [comment]
Oh, I was a minute late.

**Comment by Rupeshiya** [comment]
No worries ,your PR will be counted for hacktoberfest ,and I will merge the one which will be better but always assign the issue to yourself before PR.

**Comment by sterjoski** [comment]
Will do! @Rupeshiya
